export const authConstants = {
    LOGIN_REQUEST : 'LOGIN_REQUEST' ,
    LOGIN_FAILURE : 'LOGIN_FAILURE' ,
    LOGIN_SUCCESS : 'LOGIN_SUCCESS' ,
    LOGOUT_REQUEST : 'LOGOUT_REQUEST',
    LOGOUT_SUCCESS : 'LOGOUT_SUCCESS',
    LOGOUT_FAILURE : 'LOGOUT_FAILURE'

}

export const userConstants = {
    USER_REGISTER_REQUEST : 'USER_REGISTER_REQUEST',
    USER_REGISTER_SUCCESS : 'USER_REGISTER_SUCCESS',
    USER_REGISTER_FAILURE : 'USER_REGISTER_FAILURE'
}

export const ideesConstants = {
    GET_ALL_IDEES_REQUEST : 'GET_ALL_IDEES_REQUEST',
    GET_ALL_IDEES_SUCCESS : 'GET_ALL_IDEES_SUCCESS',
    GET_ALL_IDEES_FAILURE : 'GET_ALL_IDEES_FAILURE',
    ADD_NEW_IDEE_REQUEST : 'ADD_NEW_IDEE_REQUEST',
    ADD_NEW_IDEE_SUCCESS : 'ADD_NEW_IDEE_SUCCESS',
    ADD_NEW_IDEE_FAILURE : 'ADD_NEW_IDEE_FAILURE'

}

export const usersConstants = {
    GET_ALL_USERS_REQUEST : 'GET_ALL_USERS_REQUEST',
    GET_ALL_USERS_SUCCESS : 'GET_ALL_USERS_SUCCESS',
    GET_ALL_USERS_FAILURE : 'GET_ALL_USERS_FAILURE',
    GET_NEW_USER_REQUEST : 'GET_NEW_USER_REQUEST',
    GET_NEW_USER_REQUEST : 'GET_NEW_USER_REQUEST',
    GET_NEW_USER_REQUEST : 'GET_NEW_USER_REQUEST'

}


export const initialDataConstants = {
    GET_ALL_INITIAL_DATA_REQUEST : 'GET_ALL_INITIAL_DATA_REQUEST',
    GET_ALL_INITIAL_DATA_SUCCESS : 'GET_ALL_INITIAL_DATA_SUCCESS',
    GET_ALL_INITIAL_DATA_FAILURE : 'GET_ALL_INITIAL_DATA_FAILURE'
}