export const authConstants = {
    LOGIN_REQUEST : 'LOGIN_REQUEST' ,
    LOGIN_FAILURE : 'LOGIN_FAILURE' ,
    LOGIN_SUCCESS : 'LOGIN_SUCCESS' ,
    LOGOUT_REQUEST : 'LOGOUT_REQUEST',
    LOGOUT_SUCCESS : 'LOGOUT_SUCCESS',
    LOGOUT_FAILURE : 'LOGOUT_FAILURE'

}

export const userConstants = {
    USER_REGISTER_REQUEST : 'USER_REGISTER_REQUEST',
    USER_REGISTER_SUCCESS : 'USER_REGISTER_SUCCESS',
    USER_REGISTER_FAILURE : 'USER_REGISTER_FAILURE'
}

export const ideesConstants = {
    GET_ALL_IDEES_REQUEST : 'GET_ALL_IDEES_REQUEST',
    GET_ALL_IDEES_SUCCESS : 'GET_ALL_IDEES_SUCCESS',
    GET_ALL_IDEES_FAILURE : 'GET_ALL_IDEES_FAILURE',
    ADD_NEW_IDEE_REQUEST : 'ADD_NEW_IDEE_REQUEST',
    ADD_NEW_IDEE_SUCCESS : 'ADD_NEW_IDEE_SUCCESS',
    ADD_NEW_IDEE_FAILURE : 'ADD_NEW_IDEE_FAILURE',
    VALIDATE_IDEE_SUCCESS : 'VALIDATE_IDEE_SUCCESS',
    VALIDATE_IDEE_FAILURE : 'VALIDATE_IDEE_FAILURE',
    DELETE_IDEE_SUCCESS : 'DELETE_IDEE_SUCCESS',
    DELETE_IDEE_FAILURE : 'DELETE_IDEE_FAILURE',
    GET_IDEE_SUCCESS : 'GET_IDEE_SUCCESS',
    GET_IDEE_FAILURE : 'GET_IDEE_FAILURE',
    GET_MES_IDEES_REQUEST : 'GET_MES_IDEES_REQUEST',
    GET_MES_IDEES_SUCCESS : 'GET_MES_IDEES_SUCCESS',
    GET_MES_IDEES_FAILURE : 'GET_MES_IDEES_FAILURE'

}

export const projetsConstants = {
    GET_ALL_PROJETS_REQUEST : 'GET_ALL_PROJETS_REQUEST',
    GET_ALL_PROJETS_SUCCESS : 'GET_ALL_PROJETS_SUCCESS',
    GET_ALL_PROJETS_FAILURE : 'GET_ALL_PROJETS_FAILURE',
    ADD_NEW_PROJET_REQUEST : 'ADD_NEW_PROJET_REQUEST',
    ADD_NEW_PROJET_SUCCESS : 'ADD_NEW_PROJET_SUCCESS',
    ADD_NEW_PROJET_FAILURE : 'ADD_NEW_PROJET_FAILURE',
    GET_PROJET_SUCCESS : 'GET_PROJET_SUCCESS',
    GET_PROJET_FAILURE : 'GET_PROJET_FAILURE',
    GET_MES_PROJETS_REQUEST : 'GET_MES_PROJETS_REQUEST',
    GET_MES_PROJETS_SUCCESS : 'GET_MES_PROJETS_SUCCESS',
    GET_MES_PROJETS_FAILURE : 'GET_MES_PROJETS_FAILURE'

}

export const usersConstants = {
    GET_ALL_USERS_REQUEST : 'GET_ALL_USERS_REQUEST',
    GET_ALL_USERS_SUCCESS : 'GET_ALL_USERS_SUCCESS',
    GET_ALL_USERS_FAILURE : 'GET_ALL_USERS_FAILURE',
    GET_NEW_USER_REQUEST : 'GET_NEW_USER_REQUEST',
    GET_NEW_USER_REQUEST : 'GET_NEW_USER_REQUEST',
    GET_NEW_USER_REQUEST : 'GET_NEW_USER_REQUEST',
    DELETE_USER_SUCCESS : 'DELETE_USER_SUCCESS',
    DELETE_USER_FAILURE : 'DELETE_USER_FAILURE'

}


export const commentairesConstants = {
    GET_ALL_COMMENTAIRES_REQUEST : 'GET_ALL_COMMENTAIRES_REQUEST',
    GET_ALL_COMMENTAIRES_SUCCESS : 'GET_ALL_COMMENTAIRES_SUCCESS',
    GET_ALL_COMMENTAIRES_FAILURE : 'GET_ALL_COMMENTAIRES_FAILURE',
    GET_PROJET_COMMENTAIRES_SUCCESS : 'GET_PROJET_COMMENTAIRES_SUCCESS',
    GET_PROJET_COMMENTAIRES_FAILURE : 'GET_PROJET_COMMENTAIRES_FAILURE',
    DELETE_COMMENTAIRE_SUCCESS : 'DELETE_COMMENTAIRE_SUCCESS',
    DELETE_COMMENTAIRE_FAILURE : 'DELETE_COMMENTAIRE_FAILURE',
    ADD_COMMENTAIRE_SUCCESS : 'ADD_COMMENTAIRE_SUCCESS',
    ADD_COMMENTAIRE_FAILURE : 'ADD_COMMENTAIRE_FAILURE'
}


export const presentationsConstants = {
    GET_ALL_PRESENTATIONS_REQUEST : 'GET_ALL_PRESENTATIONS_REQUEST',
    GET_ALL_PRESENTATIONS_SUCCESS : 'GET_ALL_PRESENTATIONS_SUCCESS',
    GET_ALL_PRESENTATIONS_FAILURE : 'GET_ALL_PRESENTATIONS_FAILURE',
    GET_PROJET_PRESENTATION_SUCCESS : 'GET_PROJET_PRESENTATION_SUCCESS',
    GET_PROJET_PRESENTATION_FAILURE : 'GET_PROJET_PRESENTATION_FAILURE',
    DELETE_PRESENTATION_SUCCESS : 'DELETE_PRESENTATION_SUCCESS',
    DELETE_PRESENTATION_FAILURE : 'DELETE_PRESENTATION_FAILURE',
    ADD_PRESENTATION_SUCCESS : 'ADD_PRESENTATION_SUCCESS',
    ADD_PRESENTATION_FAILURE : 'ADD_PRESENTATION_FAILURE'
}

export const rapportsConstants = {
    GET_ALL_RAPPORTS_REQUEST : 'GET_ALL_RAPPORTS_REQUEST',
    GET_ALL_RAPPORTS_SUCCESS : 'GET_ALL_RAPPORTS_SUCCESS',
    GET_ALL_RAPPORTS_FAILURE : 'GET_ALL_RAPPORTS_FAILURE',
    GET_PROJET_RAPPORT_SUCCESS : 'GET_PROJET_RAPPORT_SUCCESS',
    GET_PROJET_RAPPORT_FAILURE : 'GET_PROJET_RAPPORT_FAILURE',
    DELETE_RAPPORT_SUCCESS : 'DELETE_RAPPORT_SUCCESS',
    DELETE_RAPPORT_FAILURE : 'DELETE_RAPPORT_FAILURE',
    ADD_RAPPORT_SUCCESS : 'ADD_RAPPORT_SUCCESS',
    ADD_RAPPORT_FAILURE : 'ADD_RAPPORT_FAILURE'
}

export const evaluationsConstants = {
    GET_ALL_EVALUATIONS_REQUEST : 'GET_ALL_EVALUATIONS_REQUEST',
    GET_ALL_EVALUATIONS_SUCCESS : 'GET_ALL_EVALUATIONS_SUCCESS',
    GET_ALL_EVALUATIONS_FAILURE : 'GET_ALL_EVALUATIONS_FAILURE',
    GET_PROJET_EVALUATION_SUCCESS : 'GET_PROJET_EVALUATION_SUCCESS',
    GET_PROJET_EVALUATION_FAILURE : 'GET_PROJET_EVALUATION_FAILURE',
    DELETE_EVALUATION_SUCCESS : 'DELETE_EVALUATION_SUCCESS',
    DELETE_EVALUATION_FAILURE : 'DELETE_EVALUATION_FAILURE',
    ADD_EVALUATION_SUCCESS : 'ADD_EVALUATION_SUCCESS',
    ADD_EVALUATION_FAILURE : 'ADD_EVALUATION_FAILURE'
}