export const authConstants = {
    LOGIN_REQUEST : 'LOGIN_REQUEST' ,
    LOGIN_FAILURE : 'LOGIN_FAILURE' ,
    LOGIN_SUCCESS : 'LOGIN_SUCCESS' ,
    LOGOUT_REQUEST : 'LOGOUT_REQUEST',
    LOGOUT_SUCCESS : 'LOGOUT_SUCCESS',
    LOGOUT_FAILURE : 'LOGOUT_FAILURE'

}

export const userConstants = {
    USER_REGISTER_REQUEST : 'USER_REGISTER_REQUEST',
    USER_REGISTER_SUCCESS : 'USER_REGISTER_SUCCESS',
    USER_REGISTER_FAILURE : 'USER_REGISTER_FAILURE'
}

export const ideesConstants = {
    GET_ALL_IDEES_REQUEST : 'GET_ALL_IDEES_REQUEST',
    GET_ALL_IDEES_SUCCESS : 'GET_ALL_IDEES_SUCCESS',
    GET_ALL_IDEES_FAILURE : 'GET_ALL_IDEES_FAILURE',
    ADD_NEW_IDEE_REQUEST : 'ADD_NEW_IDEE_REQUEST',
    ADD_NEW_IDEE_SUCCESS : 'ADD_NEW_IDEE_SUCCESS',
    ADD_NEW_IDEE_FAILURE : 'ADD_NEW_IDEE_FAILURE',
    VALIDATE_IDEE_SUCCESS : 'VALIDATE_IDEE_SUCCESS',
    VALIDATE_IDEE_FAILURE : 'VALIDATE_IDEE_FAILURE',
    DELETE_IDEE_SUCCESS : 'DELETE_IDEE_SUCCESS',
    DELETE_IDEE_FAILURE : 'DELETE_IDEE_FAILURE'

}

export const projetsConstants = {
    GET_ALL_PROJETS_REQUEST : 'GET_ALL_PROJETS_REQUEST',
    GET_ALL_PROJETS_SUCCESS : 'GET_ALL_PROJETS_SUCCESS',
    GET_ALL_PROJETS_FAILURE : 'GET_ALL_PROJETS_FAILURE',
    ADD_NEW_PROJET_REQUEST : 'ADD_NEW_PROJET_REQUEST',
    ADD_NEW_PROJET_SUCCESS : 'ADD_NEW_PROJET_SUCCESS',
    ADD_NEW_PROJET_FAILURE : 'ADD_NEW_PROJET_FAILURE'

}

export const usersConstants = {
    GET_ALL_USERS_REQUEST : 'GET_ALL_USERS_REQUEST',
    GET_ALL_USERS_SUCCESS : 'GET_ALL_USERS_SUCCESS',
    GET_ALL_USERS_FAILURE : 'GET_ALL_USERS_FAILURE',
    GET_NEW_USER_REQUEST : 'GET_NEW_USER_REQUEST',
    GET_NEW_USER_REQUEST : 'GET_NEW_USER_REQUEST',
    GET_NEW_USER_REQUEST : 'GET_NEW_USER_REQUEST',
    DELETE_USER_SUCCESS : 'DELETE_USER_SUCCESS',
    DELETE_USER_FAILURE : 'DELETE_USER_FAILURE'

}


export const commentairesConstants = {
    GET_ALL_COMMENTAIRES_REQUEST : 'GET_ALL_COMMENTAIRES_REQUEST',
    GET_ALL_COMMENTAIRES_SUCCESS : 'GET_ALL_COMMENTAIRES_SUCCESS',
    GET_ALL_COMMENTAIRES_FAILURE : 'GET_ALL_COMMENTAIRES_FAILURE',
    DELETE_COMMENTAIRE_SUCCESS : 'DELETE_COMMENTAIRE_SUCCESS',
    DELETE_COMMENTAIRE_FAILURE : 'DELETE_COMMENTAIRE_FAILURE'
}